<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Bizcord.ChannelService.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChannelService.Domain\ChannelService.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\packages\MessageClient\src\MessageClient.csproj" />
    <ProjectReference Include="..\..\..\..\packages\Messages\Messages.csproj" />
  </ItemGroup>
</Project>
